# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 18:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ankieta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(default=datetime.datetime(2017, 1, 17, 18, 18, 58, 959000, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to='ankieta.Question'),
            preserve_default=False,
        ),
    ]
